name = "telegram-group-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "d19e046ab1174544b19f96d92771fac0"

# Allow importing .html files as text strings
[[rules]]
type = "Text"
globs = ["**/*.html"]
